version: 2

defaults: &defaults
  working_directory: ~/project/vue-router-lite
  docker:
    - image: circleci/node:lts-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-router-lite-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-vue-router-lite-{{ .Branch }}-
            - v1-vue-router-lite
      - restore_cache:
          keys:
            - v1-vue-router-lite-docs-{{ .Branch }}-{{ checksum "docs/package-lock.json" }}
            - v1-vue-router-lite-docs-{{ .Branch }}-
            - v1-vue-router-lite-docs
      - run: npm install && cd docs && npm install
      - save_cache:
          key: v1-vue-router-lite-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - save_cache:
          key: v1-vue-router-lite-docs-{{ .Branch }}-{{ checksum "docs/package-lock.json" }}
          paths:
            - docs/node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-router-lite

  docs-examples:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e6:03:a3:2c:0c:7f:18:c8:9a:ac:57:92:c8:f4:8a:a6"
      - attach_workspace:
          at: ~/project
      # init gh-pages
      - run: cd ../ && mkdir gh-pages
      # docs
      - run: VUEPRESS_BASE=/vue-router-lite/docs/ npm run docs:build && cp -r docs/.vuepress/dist ../gh-pages/docs 
      # examples
      - run: PUBLIC_PATH=/vue-router-lite/examples/ npm run examples:build && cp -r examples/__build__ ../gh-pages/examples 
      # push
      - run: cd ../gh-pages && git init && git config --global user.email "season.chen.i@foxmail.com" && git config --global user.name "Season Chen" && git add -A && git commit -m 'deploy [ci skip]' && git push -f git@github.com:ccqgithub/vue-router-lite.git master:gh-pages

  # lint-flow-types:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run lint
  #     - run: yarn run flow
  #     - run: yarn run test:types

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test
      # add codecov once it is actually ran
      # - run:
      #    name: report coverage stats for non-PRs
      #    command: |
      #      if [[ -z $CI_PULL_REQUEST ]]; then
      #        ./node_modules/.bin/codecov
      #      fi

  # test-e2e:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run test:e2e

  # test-e2e-bs-ie9:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run test:e2e:ie9

workflows:
  version: 2
  all:
    jobs:
      - install:
          requires:
            - install
          filters:
            branches:
              only: master
      - docs-examples:
          requires:
            - install
          filters:
            branches:
              only: master
      - test-unit:
          requires:
            - install
          filters:
            branches:
              only: master
      # - lint-flow-types:
      #     requires:
      #       - install
      # - test-e2e:
      #     requires:
      #       - install
      # - test-e2e-bs-ie9:
      #     requires:
      #       - install
