version: 2

defaults: &defaults
  working_directory: ~/project/vue-router-lite
  docker:
    - image: circleci/node:lts-browsers

jobs:
  deploy-docs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-router-lite-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-vue-router-lite-{{ .Branch }}-
            - v1-vue-router-lite
      - run: npm install
      - save_cache:
          key: v1-vue-router-lite-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      # 生成静态文件
      - run: npm run docs:build
      - run: cd docs/.vuepress/dist && git init && git config --global user.email "season.chen.i@foxmail.com" && git config --global user.name "Season Chen"
      - run: cd docs/.vuepress/dist && git add -A && git commit -m 'deploy' && git push -f git@github.com:ccqgithub/vue-router-lite.git master:gh-pages
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-router-lite

  # lint-flow-types:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run lint
  #     - run: yarn run flow
  #     - run: yarn run test:types

  # test-unit:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run test:unit
  #     # add codecov once it is actually ran
  #     # - run:
  #     #    name: report coverage stats for non-PRs
  #     #    command: |
  #     #      if [[ -z $CI_PULL_REQUEST ]]; then
  #     #        ./node_modules/.bin/codecov
  #     #      fi

  # test-e2e:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run test:e2e

  # test-e2e-bs-ie9:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: yarn run test:e2e:ie9

workflows:
  version: 2
  install-workflows:
    jobs:
      - deploy-docs
      # - docs:
      #     requires:
      #       - install
      # - test-unit:
      #     requires:
      #       - install
      # - lint-flow-types:
      #     requires:
      #       - install
      # - test-e2e:
      #     requires:
      #       - install
      # - test-e2e-bs-ie9:
      #     requires:
      #       - install
